version: "3"
services:
    website:
        image: node:12
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        environment:
            - APP_ENV=production
            - NODE_ENV=production
